build:
  maxIssues: 1000
  weights:
    complexity: 0
    LongParameterList: 0

processors:
  active: false

formatting:
  active: true
  autoCorrect: true
  Indentation:
    active: true
    indentSize: 4
  NoWildcardImports:
    active: false
  SpacingAroundComma:
    active: false
  SpacingAroundKeyword:
    active: false

style:
  FunctionNaming:
    active: false
  ClassNaming:
    active: false
  MagicNumber:
    active: false
  WildcardImport:
    active: false