name: KMP Linting

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ktlint-check:
    name: ktlint Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Attempt Auto-fix
        run: |
          ./gradlew ktlintFormat
          git diff --quiet || (git config --global user.email "ci@example.com" && \
          git config --global user.name "CI Bot" && \
          git commit -am "ktlint auto-fix [skip ci]" && \
          git push)

      - name: Run ktlint
        run: ./gradlew ktlintCheck

  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            task: :shared:jvmTest
          - os: macos-latest
            task: :shared:iosSimulatorArm64Test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run Common Tests
        run: ./gradlew :shared:commonTest

      - name: Run Platform Tests
        run: ./gradlew ${{ matrix.task }}
